/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo {
  'instagram' : string,
  'email' : string,
  'phone' : string,
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface ModelStats {
  'height' : number,
  'hips' : number,
  'chest' : number,
  'experience' : bigint,
  'shoes' : number,
  'agencyName' : string,
  'agencyUrl' : string,
  'waist' : number,
}
export interface Photo {
  'id' : string,
  'blob' : ExternalBlob,
  'displayOrder' : bigint,
  'createdAt' : bigint,
  'caption' : string,
  'category' : PhotoCategory,
}
export type PhotoCategory = { 'commercial' : null } |
  { 'editorial' : null } |
  { 'runway' : null } |
  { 'lifestyle' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPhoto' : ActorMethod<[Photo], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'getAllPhotos' : ActorMethod<[], Array<Photo>>,
  'getBio' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], [] | [ContactInfo]>,
  'getModelStats' : ActorMethod<[], [] | [ModelStats]>,
  'getPhoto' : ActorMethod<[string], Photo>,
  'getPhotosByCategory' : ActorMethod<[PhotoCategory], Array<Photo>>,
  'getSectionOrder' : ActorMethod<[], Array<string>>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderPhotos' : ActorMethod<[Array<string>], undefined>,
  'updateBio' : ActorMethod<[string], undefined>,
  'updateContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'updateModelStats' : ActorMethod<[ModelStats], undefined>,
  'updatePhoto' : ActorMethod<[Photo], undefined>,
  'updateSectionOrder' : ActorMethod<[Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];