/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PhotoCategory = IDL.Variant({
  'commercial' : IDL.Null,
  'editorial' : IDL.Null,
  'runway' : IDL.Null,
  'lifestyle' : IDL.Null,
});
export const Photo = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'displayOrder' : IDL.Nat,
  'createdAt' : IDL.Int,
  'caption' : IDL.Text,
  'category' : PhotoCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactInfo = IDL.Record({
  'instagram' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const ModelStats = IDL.Record({
  'height' : IDL.Float64,
  'hips' : IDL.Float64,
  'chest' : IDL.Float64,
  'experience' : IDL.Nat,
  'shoes' : IDL.Float64,
  'agencyName' : IDL.Text,
  'agencyUrl' : IDL.Text,
  'waist' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPhoto' : IDL.Func([Photo], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getBio' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
  'getModelStats' : IDL.Func([], [IDL.Opt(ModelStats)], ['query']),
  'getPhoto' : IDL.Func([IDL.Text], [Photo], ['query']),
  'getPhotosByCategory' : IDL.Func(
      [PhotoCategory],
      [IDL.Vec(Photo)],
      ['query'],
    ),
  'getSectionOrder' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderPhotos' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateBio' : IDL.Func([IDL.Text], [], []),
  'updateContactInfo' : IDL.Func([ContactInfo], [], []),
  'updateModelStats' : IDL.Func([ModelStats], [], []),
  'updatePhoto' : IDL.Func([Photo], [], []),
  'updateSectionOrder' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PhotoCategory = IDL.Variant({
    'commercial' : IDL.Null,
    'editorial' : IDL.Null,
    'runway' : IDL.Null,
    'lifestyle' : IDL.Null,
  });
  const Photo = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'displayOrder' : IDL.Nat,
    'createdAt' : IDL.Int,
    'caption' : IDL.Text,
    'category' : PhotoCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactInfo = IDL.Record({
    'instagram' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const ModelStats = IDL.Record({
    'height' : IDL.Float64,
    'hips' : IDL.Float64,
    'chest' : IDL.Float64,
    'experience' : IDL.Nat,
    'shoes' : IDL.Float64,
    'agencyName' : IDL.Text,
    'agencyUrl' : IDL.Text,
    'waist' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPhoto' : IDL.Func([Photo], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getBio' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
    'getModelStats' : IDL.Func([], [IDL.Opt(ModelStats)], ['query']),
    'getPhoto' : IDL.Func([IDL.Text], [Photo], ['query']),
    'getPhotosByCategory' : IDL.Func(
        [PhotoCategory],
        [IDL.Vec(Photo)],
        ['query'],
      ),
    'getSectionOrder' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderPhotos' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateBio' : IDL.Func([IDL.Text], [], []),
    'updateContactInfo' : IDL.Func([ContactInfo], [], []),
    'updateModelStats' : IDL.Func([ModelStats], [], []),
    'updatePhoto' : IDL.Func([Photo], [], []),
    'updateSectionOrder' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };